"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Building2, CreditCard, Search, ShieldAlert, Users, RefreshCw, LockKeyhole, BarChart3 } from "lucide-react";
import { useAuth } from "@/lib/firebase/AuthProvider";

type Business = { id: string; name?: string; industry?: string; email?: string; phone?: string; createdAt?: string; memberCount?: number; subscription?: { plan?: string; status?: string; currentPeriodEnd?: string } };
export default function AdminHome() {
  const auth = useAuth(); const [rows, setRows] = useState<Business[]>([]); const [q, setQ] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const load = async () => { if (!auth.fbUser) return; setLoading(true); setError(""); try { const token = await auth.fbUser.getIdToken(); const r = await fetch("/api/admin/businesses", { headers: { Authorization: `Bearer ${token}` } }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setRows(data.businesses); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load admin data"); } finally { setLoading(false); } };
  useEffect(() => { if (auth.ready && auth.fbUser) void load(); }, [auth.ready, auth.fbUser]);
  const filtered = useMemo(() => rows.filter((b) => `${b.name ?? ""} ${b.email ?? ""} ${b.phone ?? ""}`.toLowerCase().includes(q.toLowerCase())), [rows, q]);
  if (!auth.ready) return <AdminMessage text="Checking administrator access…" />;
  if (auth.mode !== "firebase") return <AdminMessage text="Platform administration requires Firebase mode and server credentials." />;
  if (!auth.fbUser) return <AdminMessage text="Sign in with an administrator account to continue." link="/login" />;
  const premium = rows.filter((b) => b.subscription?.plan === "premium").length;
  return <div className="space-y-5 text-slate-100"><div><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-emerald-400">Platform operations</p><h1 className="mt-1 text-2xl font-bold">System administrator</h1><p className="mt-1 text-sm text-slate-400">Manage accounts, subscriptions and platform access.</p></div><button onClick={() => void load()} className="rounded-xl border border-slate-700 px-3 py-2 text-sm hover:bg-slate-800"><RefreshCw size={15} className={loading ? "animate-spin" : ""} /></button></div></div>
    {error && <div className="rounded-xl border border-rose-800 bg-rose-950/50 p-3 text-sm text-rose-200">{error}. Confirm your Firebase user has a platform admin custom claim.</div>}
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric icon={Building2} label="Businesses" value={rows.length} /><Metric icon={CreditCard} label="Premium" value={premium} /><Metric icon={Users} label="Free" value={rows.length - premium} /><Link href="/admin/support" className="rounded-2xl border border-slate-800 bg-slate-900 p-4 hover:border-emerald-600"><ShieldAlert className="text-amber-400" size={18}/><div className="mt-3 text-xl font-bold">Support access</div><div className="text-xs text-slate-400">Time-limited read-only</div></Link><Link href="/admin/security" className="rounded-2xl border border-slate-800 bg-slate-900 p-4 hover:border-emerald-600"><LockKeyhole className="text-emerald-400" size={18}/><div className="mt-3 text-xl font-bold">Security</div><div className="text-xs text-slate-400">MFA settings</div></Link><Link href="/admin/analytics" className="rounded-2xl border border-slate-800 bg-slate-900 p-4 hover:border-emerald-600"><BarChart3 className="text-sky-400" size={18}/><div className="mt-3 text-xl font-bold">Analytics</div><div className="text-xs text-slate-400">Usage and health</div></Link><Link href="/admin/audit" className="rounded-2xl border border-slate-800 bg-slate-900 p-4 hover:border-emerald-600"><ShieldAlert className="text-amber-400" size={18} /><div className="mt-3 text-xl font-bold">Audit</div><div className="text-xs text-slate-400">Platform activity</div></Link></div>
    <section className="rounded-2xl border border-slate-800 bg-slate-900"><div className="flex flex-wrap items-center gap-3 border-b border-slate-800 p-4"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-2.5 text-slate-500" /><input className="w-full rounded-xl border border-slate-700 bg-slate-950 px-9 py-2 text-sm text-white outline-none focus:border-emerald-500" placeholder="Search businesses" value={q} onChange={(e) => setQ(e.target.value)} /></div><span className="text-xs text-slate-500">{filtered.length} shown</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Business</th><th className="px-4 py-3">Plan</th><th className="px-4 py-3">Members</th><th className="px-4 py-3">Created</th><th /></tr></thead><tbody>{filtered.map((b) => <tr key={b.id} className="border-t border-slate-800"><td className="px-4 py-3"><div className="font-medium">{b.name || "Unnamed business"}</div><div className="text-xs text-slate-500">{b.email || b.phone || b.id}</div></td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs ${b.subscription?.plan === "premium" ? "bg-emerald-950 text-emerald-300" : "bg-slate-800 text-slate-300"}`}>{b.subscription?.plan ?? "free"} · {b.subscription?.status ?? "free"}</span></td><td className="px-4 py-3 text-slate-400">{b.memberCount ?? 0}</td><td className="px-4 py-3 text-slate-400">{b.createdAt ? new Date(b.createdAt).toLocaleDateString("en-GB") : "—"}</td><td className="px-4 py-3 text-right"><Link href={`/admin/businesses/${b.id}`} className="text-emerald-400 hover:underline">View</Link></td></tr>)}{!filtered.length && <tr><td colSpan={5} className="p-8 text-center text-slate-500">No businesses found.</td></tr>}</tbody></table></div></section>
  </div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Building2; label: string; value: number }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><Icon size={18} className="text-emerald-400" /><div className="mt-3 text-2xl font-bold">{value}</div><div className="text-xs text-slate-400">{label}</div></div> }
function AdminMessage({ text, link }: { text: string; link?: string }) { return <div className="flex min-h-[60vh] items-center justify-center"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-8 text-center text-slate-300"><ShieldAlert className="mx-auto mb-3 text-amber-400" /><p>{text}</p>{link && <Link href={link} className="mt-4 inline-block text-emerald-400 underline">Sign in</Link>}</div></div> }
